### PR TITLE
Add possibility to fetch and embed graphs from remote server

### PR DESCRIPTION
**Pull request by xert**
Add possibility to fetch and embed graphs from remote server accessible to icingaweb2 user.

For example local graphite installation not exposed to public or a password protected instance.

New config variables:

remote_fetch = true
remote_verify_peer = true
remote_verify_peer_name = true

### CODE REVIEW

**Comment by philiphoy** [comment]
@xert I am sorry to leave this pull hanging but i think it is rare that users of icinga cannot also access the graphite instance so i am a bit hesitant to accept this for now as it is quite a large change. I will leave it open for now so anyone else can +1 it.

**Comment by phibos** [comment]
:+1: This is a feature I was looking for.

**Comment by DMajrekar** [comment]
I would also be interested in this feature. 

It would allow controlled access to data in a multi tenant environment.

**Comment by xert** [comment]
I will update this to allow merging without conflicts. I just need to wait for Icinga 2.4 to compile without errors on FreeBSD 93amd64.

**Comment by philiphoy** [comment]
Ok it looks like my assumption was wrong and this feature would be useful to people. Awaiting you update....

**Comment by xert** [comment]
I am blocked by this issue - https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=204723 
I will update the patch as soon as this is resolved.

**Comment by xert** [comment]
I messed up my repo a bit, so I will create a new pull request for this feature.

**Pull request closed without merging**
