### PR TITLE
Add threshold lines for warning and critical to graphs

### PR DESCRIPTION
**Pull request by sargon**
The information level of graphs without scaling is small.
Threshold lines gives them an easy to judge scale.

### CODE REVIEW

**Comment by philiphoy** [comment]
I think i would prefer that any graphite graph tweaking was done via the existing template methods ($largeImageUrlMacro, $ImageUrlMacro) otherwise the parameters will most likely proliferate further as people shape the graphs to their preferred configuration.

**Comment by sargon** [comment]
And how are you going to get the service dependent values for the thresholds (warning,critical)?
But, yes I could add an configuration flag, to disable this feature.

**Comment by philiphoy** [comment]
If you set enable_send_thresholds = true then you get metrics for the thresholds. https://www.icinga.org/2015/11/09/icinga-2-v2-4-new-graphite-schema/ then once #32 is sorted you should be able to add something like $target$.crit.

**Comment by sargon** [comment]
Okay. That works for me. So I will close this pr.

**Pull request closed without merging**
