### PR TITLE
Variable $legacyMode contains a string, not a boolean, so the if clau…

### PR DESCRIPTION
**Pull request by Alex9779**
…se has to be changed
As in #29 described. This fixes it...

### CODE REVIEW

**Comment by philiphoy** [comment]
Good catch, but really it should be a boolean not a string, I wonder if you could amend the pull request and make other instances of the variable a boolean.

**Comment by Alex9779** [comment]
I changed it that way because in Graphite.php there was an if clause where also that variables was checked and there it was used as a string. So I assumed this was the intention but sure I can change the whole usage to a bool...

**Comment by Alex9779** [comment]
Ok changed the variable to be a boolean.
Unfortunately the config has to be changed as far as I know. You have to pass 0 and 1 now for the correct interpretation when reading the values. `false` is interpreted as a string and then `if ($legacyMode)` is always true because the variable is assigned.
If there is an alternative please tell me, I am not so into PHP...

**Comment by philiphoy** [comment]
No i am no php expert either but it looks like: 

```
 filter_var($value, FILTER_VALIDATE_BOOLEAN) 
```

is the answer according to: http://stackoverflow.com/questions/4775294/parsing-a-string-into-a-boolean-value-in-php

Can you call that function in the GrapherHook.init perhaps and amend you pull?

**Comment by Alex9779** [comment]
Ok inserted the filter function, reversed change in the demo config...

**Comment by philiphoy** [comment]
@Alex9779  thanks for your patience and contribution.

**Pull request merged**
