### PR TITLE
Add possibility to fetch and embed graphs from remote server

### PR DESCRIPTION
**Pull request by xert**
Updated patch as promised in findmypast/icingaweb2-module-graphite/pull/26

[Review on Reviewable](https://reviewable.io/reviews/findmypast/icingaweb2-module-graphite/40)

### CODE REVIEW

**Comment by xert** [comment]
Is there any problem / doubt with this? I'll be happy to correct it.

**Comment by smelchior** [comment]
Thanks for this feature, just what i was looking for and it works very nicely!

**Comment by sashman** [comment]
Hey @smelchior and @xert, thanks for the PR and very sorry about the delayed response!

Have you by any chance had a look into the conflict here?

**Comment by xert** [comment]
@sashman I'll try to look into this and solve the conflict.

**Comment by xert** [comment]
Hi @sashman can you please look at this and possibly merge?

**Comment by sashman** [comment]
Hey @xert thanks for the fix, I have one query though, as I'm new to this chunk of code and there seems to be non-trivial changes, do you mind giving me a little run through of what this affects please? Would be very appreciated and help out loads!

**Comment by xert** [comment]
Hi @sashman, sure.

The feature here is to implement fetching the graph from remote server, if the server is not accessible from icingaweb2 users browser. This is for example when using multi-tenant icingaweb2 installation and http basic auth to icingaweb and graphite with the same credentials is not desirable.

When this feature is turned on, then the code fetches the image from remote servers and inlines the data in the img tag `` instead of simply creating the image tag ``

Is this explanation sufficient?

**Comment by friesoft** [comment]
Any news on merging this? :)

**Comment by sashman** [comment]
@xert @friesoft apologies for the delayed response, this seems sensible to me!

**Comment by friesoft** [comment]
Thank you very much for this feature :) it works great for the embedded graphs.

What doesn't work is clicking on the graphs and having it fetch it also using remote_fetch.
Our situation: we have a proxy which proxies icingaweb2. The graphite render URL isn't available externally - so now we have the small embedded graphs when accessing icingaweb2 externally but not the whole graph when clicking on the small ones.
Any chance this could also be implemented?

**Comment by xert** [comment]
Hi @friesoft 

can You post your config and what link is generated on your small images (pointing to larger ones)? I'm using this in similar setup (for this reason I've made this PR) and both small and large graphs are embedded. Are You using current master?

**Comment by friesoft** [comment]
I guess our problem is with http/https. Our proxy is https and we are using ProxyPass + ProxyPassReverse to icingaweb2 (+graphite) running on http.

We also didn't have ProxyPreserveHost set which led to the following code not working:

application/controllers/IndexController.php:22
```
        if ($this->grapher->getRemoteFetch()) {                   
            $this->view->url = $this->_request->getScheme()."://".
                               $this->_request->getHttpHost().
```
getHttpHost returned our internal URL to icingaweb2.
With ProxyPreserveHost this correctly returns our proxy host but getScheme returns the scheme of our internal URL (http). This still leads to not working requests as we now get mixed content warnings in the browsers.
[Edit]: in Internet Explorer 11 it is working now as it completely ignores mixed content warnings..
Firefox/Chrome aren't working.

**Comment by friesoft** [comment]
My workaround for the moment:
```
        $scheme = $this->_request->getScheme();
        if ($this->_request->getHeader("X_FORWARDED_PROTO")) {
            $scheme = $this->_request->getHeader("X_FORWARDED_PROTO");
        }
        if ($this->grapher->getRemoteFetch()) {                               
            $this->view->url = $scheme."://".
```

And my apache config:
```
  <Location "/icingaweb2">
    ProxyPreserveHost On
    RequestHeader set X-FORWARDED-PROTO https
    ProxyPass http://192.168.0.51/icingaweb2
    ProxyPassReverse http://192.168.0.51/icingaweb2
  </Location>
```

**Comment by xert** [comment]
Ah, I see. I think that's Zend Framework issue - getScheme() or URL view helper does not reflect on Proxy headers.

I see two solutions for this:

1. Something like Your workaround (seems ok for me)
2. Add icinga_base_url config option and construct url from this, not from getScheme / getHost.

@sashman - What do You think?

**Comment by friesoft** [comment]
@xert ping :) can my workaround be upstreamed?

**Comment by xert** [comment]
@friesoft please make a new pull request as there is no way @sashman can merge this.

**Pull request merged**
